### ISSUE TITLE
[Bug] The application can't be opened

### ISSUE THREAD

**Issue by 3raxton** [CrispyBaccoon/Forest#1]
Hey there,

Thanks for the hard work on Forest and keeping updates from Left open source, I know this repo will grow. I downloaded the app from the x64 Darwin zip and can't open Forest. I'm not sure why but every time I try to this comes up. I've tried to run with chmod and still nothing. 

![image](https://user-images.githubusercontent.com/20716142/154769663-45b2ef12-e156-4ac8-a4ad-159d24586ad5.png)

Do you have any ideas what I could do to resolve this or how I could get this as a .app?

Thanks again for the hard work! 🎉

**Comment by CrispyBaccoon** [comment]
Thanks for the feedback. I'm still in high school so i'm pretty busy, but i'll try to fix your problem when i find the time.

I don't know if this solves your problem, but you could download the source code from one of the releases and start the application in dev mode. Unfortunately this won't start the application as a proper executable.

**Comment by CrispyBaccoon** [comment]
After researching i've found that the default _Archive Utility_ is common to break applications. Maybe try a different application like [The Unarchiver](https://theunarchiver.com/) to extract the zip file.

**Comment by piaci** [comment]
having the same issue, does not matter what unarchiver app trying. none of any releases working.

**Comment by 3raxton** [comment]
I can finally reply with context. You're right @3raxton
